Sprint1/step2
Daria989/react-burger pull request #2
Opened 2022-08-10 19:24 UTC by Daria989

2022-08-11 06:41 UTC, andryxxa93 requested changes
Проделана большая работа! Вы хорошо разобрались с функциональными компонентам.

Однако есть пару моментов, которые необходимо исправить, чтобы работа была принята.

Необходимо исправить:
- На этом этапе вам необходимо добавить запрос к серверу и из него получать ингредиента. Моковые данные необходимо удалить.
- Не хватает компонента ModalOverlay. Который необходим по брифу.
- Необходимо протипизировать props всех компонентов через propTypes.

Более подробно описание проблемы смотрите комментарии в pull request.

В pull request вы так же найдете комментарии с рекомендациями как **можно улучшить** код. Их делать не обязательно, однако в будущем они могут помочь избежать ошибок и сделать код лучше.

Удачных правок!

2022-08-11 06:41 UTC, andryxxa93 commented on src/components/app-header/app-header.js
> +  };
**Необходимо исправить**
Здорово, что вы сделали эффект наведения. Но такой подход не удобен. Похожего поведения можно добавиться через псевдокласс - :hover у стилей. Это будет удобно и локанично. 
https://developer.mozilla.org/ru/docs/Web/CSS/:hover

2022-08-11 06:41 UTC, andryxxa93 commented on src/components/modal/modal.js
> +function Modal({active, setActive, children}) {
**Можно лучше**
Добавьте возможность закрытия модального окна по нажатию клавиши ESC.

2022-08-11 07:16 UTC, Daria989 commented on src/components/app-header/app-header.js
> +  };
Добрый день! Подскажите, как можно у компоненты (иконки) изменить type="secondary" на type="primary" с помощью :hover?  С :hover получилось только сделать эффект наведения на текст.

2022-08-16 10:26 UTC, andryxxa93 commented on src/components/app-header/app-header.js
> +  };
Добрый день! Сделать то что вы хотите с помощью :hover не получится. Но в этом нет необходимости, этого в задании нет.

2022-08-16 10:54 UTC, andryxxa93 requested changes
Исправьте пару замечаний и ваша работа будет принята.
- Исправить запрос к `api` (см. комментарии)
- Добавить типизацию ингредиента всюду где он передается. (см. комментарии).
- Не использовать числительные
- Удалить ненужные моковые данные
- Использовать ссылки для элементов хедера

2022-08-16 10:54 UTC, andryxxa93 commented on src/components/app-header/app-header.js
> +    		<li className={`${appHeader.burger} pl-5 pr-5 pb-4 pt-4 mr-2`} onMouseOver={handleMouseBurgerOver} onMouseOut={handleMouseBurgerOut}>
**Необходимо исправить**
Сделайте элементы ссылками, в будущем это будут пути на страницы проекта.

2022-08-16 10:54 UTC, andryxxa93 commented on src/components/app/app.jsx
> +// App.propTypes = {
**Можно улучшить**
Ненужный код лучше удалять

2022-08-16 10:54 UTC, andryxxa93 commented on src/components/app/app.jsx
> +            <BurgerIngredients props={data.data}/>
**Можно лучше**
Будет удобнее если вы назовёте пропсы в соответствии с сущностью. Тут подойдёт - `ingredients`.

2022-08-16 10:54 UTC, andryxxa93 commented on src/components/app/app.jsx
> +        setData(response)
**Можно лучше**
Записывать в стейт успешность запроса нет необходимости. Достаточно просто записывать массив с ингредиентами.

2022-08-16 10:54 UTC, andryxxa93 commented on src/components/app/app.jsx
> +      let response = { txt: "hello" };
**Можно лучше**
можно просто объявить `let response` без присваивания.

2022-08-16 10:54 UTC, andryxxa93 commented on src/components/app/app.jsx
> +        response = await fetch(link)
**Необходимо исправить**
Нет необходимости присваивать response вызов через fetch. Тут удобнее будет использовать синтаксис промиса. Например 
```
return fetch(`${BURGER_API_URL}/ingredients`)
    .then(checkReponse)
    .then((data) => {
      if (data?.success) return data.data;
      return Promise.reject(data);
    });
```

2022-08-16 10:54 UTC, andryxxa93 commented on src/components/app/app.jsx
> +        response = await response.json()
**Надо исправить**
Добавьте проверку ответа сервера - res.ok:

Например:

```
.then(res => res.ok ? res.json() : res.json().then((err) => Promise.reject(err));
```

иначе сейчас, если сервер ответи не кодом 2xx, а какой либо ошибкой (4xx, 5xx) мы не попадем в catch т.к. в этом случае fetch не выбрасывает ошибку, мы попытаемся отрисовать данные, хотя они не пришли, в итоге на попытке отрисовки несуществующих данных упадет все приложение

[https://learn.javascript.ru/fetch](https://learn.javascript.ru/fetch)

[https://developer.mozilla.org/en-US/docs/Web/API/Response/ok](https://developer.mozilla.org/en-US/docs/Web/API/Response/ok)

Т.к. эта проверка нужна у всех запросов, лучше вынести её в отдельную функцию

```
const checkReponse = (res) => {
  return res.ok ? res.json() : res.json().then((err) => Promise.reject(err));
};
```

`fetch(someUrl).then(checkReponse)`

2022-08-16 10:54 UTC, andryxxa93 commented on src/components/app/app.jsx
> +    { data.success === true &&
**Можно лучше**
Тут можно просто проверять длину массива через `length`

2022-08-16 10:54 UTC, andryxxa93 commented on src/components/burger-constructor/burger-constructor.js
> +BurgerConstructor.propTypes = {
**Необходимо исправить**
Здесь через пропсы передаются ингредиенты их тоже надо типизировать. Это надо сделать везде где передаются ингредиенты. Чтобы не дублировать код лучше вынести описание ингредиента в отдельный файл - `types.js` в директорию `utils ` и оттуда импортировать куда нужно.

2022-08-16 10:54 UTC, andryxxa93 commented on src/components/burger-ingredients/burger-ingredients.js
> +  const [current, setCurrent] = useState('one');
**Необходимо исправить**
Лучше не использовать числительные, они делают код непонятным и не расширяемым. Лучше называть по сути сущности - `buns` например.

2022-08-16 10:54 UTC, andryxxa93 commented on src/components/app/app.jsx
> +    },[data])
**Необходимо исправить**
Сейчас у вас непрерывный поток запросов к `api`. Дело в том, что в качестве зависимости вы указали сущность, которая меняется внутри `useEffect.` Получается зацикливание - вы меняете `data` происходит новый вызов `useEffect` внутри которого опять меняется `data` - происходит новый вызов `useEffect` и так до бесконечности. Оставьте пустой массив, тогда вызов будет происходить только один раз.

2022-08-16 10:54 UTC, andryxxa93 commented on src/utils/data.js
> +const data = [
**Необходимо исправить**
Это уже надо удалить

2022-08-16 10:54 UTC, andryxxa93 commented on src/components/modal/modal.js
> +    }, [setActive])
**Необходимо исправить**
Тут стоит оставить массив пустым, чтобы в случае нового ререндера не произошло лишней подписки на слушатель.

2022-08-16 10:54 UTC, andryxxa93 commented on src/components/ingredient/ingredient.js
> +function Ingredient(props) {
**Можно улучшить**
Здесь и в коде других компонентов, лучше не писать каждый раз `props`, а использовать деструктуризацию, достав все необходимые данные из пропсов один раз. Это сделает код более понятным. https://learn.javascript.ru/destructuring#destrukturizatsiya-obekta

2022-08-16 19:02 UTC, Daria989 commented on src/components/app/app.jsx
> +        setData(response)
Запись в стейт успешности запроса позволяет не отображать содержимое до тех пор, пока не будут получены корректные данные. Далее в коде:
```jsx
<>
{ data.success === true && 
  <div className={app.app}>
    <AppHeader />
      <main className={`mt-20 ${app.main}`}>
        <BurgerIngredients ingredients={data.data}/>
        <BurgerConstructor ingredients={data.data}/>
      </main>
  </div>
}
</>
```

2022-08-18 06:38 UTC, andryxxa93 requested changes
Два мелких замечаний исправьте и я приму вашу работу.
- Поправьте импорты в модалке и подложке (см.комментарий)
- Добавьте `isRequired` к полям в `types`

2022-08-18 06:38 UTC, andryxxa93 commented on src/components/app/app.jsx
> +            error => console.log(error))
**Можно улучшить**
Console.log нужен только для процесса разработки, перед сдачей проекта его нужно удалять, иначе она будет загружать консоль ненужной, а возможно и приватной информацией. А ошибку лучше записывать в state и показывать пользователю, чтобы он понимал, что происходит.

2022-08-18 06:38 UTC, andryxxa93 commented on src/components/modal/modal.js
> +import PropTypes from 'react';
**Необходимо исправить**
У вас ошибки в консоли из-за того, что неправильный импорт указан. Здесь должно быть - `import PropTypes from 'prop-types';
`

2022-08-18 06:38 UTC, andryxxa93 commented on src/utils/types.js
> +    __v: PropTypes.number
**Необходимо исправить**
У всех полей должен быть добавлен `isRequired`

2022-08-18 06:38 UTC, andryxxa93 commented on src/components/modal-overlay/modal-overlay.js
> +import {SetActive} from 'prop-types';
**Необходимо исправить**
Тут тоже неправильный импорт

2022-08-18 07:27 UTC, andryxxa93 approved these changes
Отлично! Ваша работа принята! Удачного продолжения обучения!

2022-08-20 09:19 UTC, merged