sprint5/step1
Daria989/react-burger pull request #7
Opened 2022-12-12 02:25 UTC by Daria989

2022-12-12 03:37 UTC, ArslanDev666 requested changes
## Code Review

Здравствуйте!

Хорошая работа.

### **Вы молодец!**

- Сборка и запуск проекта выполняются без ошибок;
- Осуществлён деплой проекта;
- Теперь в приложении есть лента заказа;
- Используются веб-сокеты;

### **Но есть несколько замечаний, которые нужно исправить:**

- Лучше поставить текст вместо нуля (например `Идёт получение номера заказа...`, но лучше всего какой-нить лоадер поставить) https://yadi.sk/d/p1ZiB4PM7_RXQg, а также после закрытия модального окна, нужно очищать стейт с номером заказа (а то остаётся старый номер, если сделать новый заказ).

- Выровняйте иконки и текст по центру, а также ссылки должны быть активными на определенных роутах. Например на роуте `/feed`, должна быть активна ссылка с текстом `Лента заказов`. И не забывайте что иконка тоже входит в ссылку.

  https://yadi.sk/d/f20GgBTWKYIgoA.

- По макету, на странице `/feed` у ленты заказов должен быть стилизованный скролл: https://yadi.sk/d/OB2MOyM_F1vkoQ;

- По макету, на странице `/feed` колонка `Готова`, должна идти первой, а также уменьшите количество столбцов до 3шт (сейчас у вас 5).

  - как в макете: https://yadi.sk/d/T0qMGR1-wLYQow;
  - как у вас: https://yadi.sk/d/2ZcMBHb3pZZVyg;

- Нужно сменить расширение у файла `utils/types.tsx` на `utils/types.ts`, т.к. в файле нету `jsx` кода;

- Добавьте отступы между элементами: https://yadi.sk/d/oTCJQ3d1ek-5PQ;

- При нажатии на кнопку выход, куки вроде очищаются, но пользователь всё равно остаётся в системе. Нужно это исправить. https://disk.yandex.ru/i/SM4kxRR8CrSRKg. Хорошо протестируйте этот момент;

- В папке `services` и не только, у всех файлов, где не используется `.jsx` должно быть расширение `ts`, а не `.tsx`, т.к. не используется `jsx`. Ну и по чек-листу: `Все файлы, относящиеся к хранилищу, имеют расширение .ts`;

- со временем приложение будет разрастаться, появится новый функционал, если все будет в одном рельюсере он станет слишком большим, разделите один большой редьюсер на несколько, обрабатывающие данные одной предметной области (одного "домена"), например

  - загрузка данных ингредиентов
  - отправка заказа
  - работа конструктора
  - открытие модального окна ингредиента

  Вижу что у вас разделён редьюсер на области, но всё находится практически в 1 файле, разделите файл на несколько. Тоже самое касается и экшенов.

### **Сделает код лучше:**

- Перенести файл `api.ts` в папку `utils`;

- При клике на таб **плавно** скролить список ингредиентов к нужному разделу;

- Стоит обращать внимание на предупреждения в терминале, в котором запущен проект. Это хорошие рекомендации, которых следовало бы придерживаться. В противном случае, лучше отключить линтер у строки (куска кода) eslint-disable. Так же добавить комментарий (TODO), объясняющий причину блокировки линтера в данном месте. Суть в том, что мы стараемся писать более чистый код, а если видим, что порой выскакивают предупреждения того же линтера, то оставляем комментарий, объясняющий причину. В коммерческой разработке, когда есть целая команда разработчиков, работающих над одним проектом, эта рекомендация послужит правилом хорошего тона. Неплохая статься по поводу локального отключения линтера: https://learn.coderslang.com/ru/0023-eslint-disable-for-specific-lines-files-and-folders;

### **_Подробно эти и более мелкие замечания, отмечены в коде._**

2022-12-12 03:37 UTC, ArslanDev666 commented on src/index.tsx
**Надо исправить:**

вынесите url адреса для сокетов, в константы. Не забывайте про `UPPER_CASE`.

2022-12-12 03:37 UTC, ArslanDev666 commented on src/components/app-header/app-header.tsx
> +  const [isProfileTextIconHovering, setProfileTextIconIsHovering] = useState<string>("pl-2 text text_type_main-default text_color_inactive");
**Надо исправить:**

здесь и далее, для ховеров у css есть псевдокласс `:hover`, лучше использовать его.

2022-12-12 03:37 UTC, ArslanDev666 commented on src/services/middleware/socketMiddlewareAuth.ts
> +export const socketMiddlewareAuth = (wsUrl: string, wsActions: TWSActionNamesAuth): Middleware => {
**Можно лучше:**

Возможно лучше написать дополнительное условие в 1 middleware, чтобы пробрасывать токен, а не делать ещё 1 файл. Тоже самое касается и экшенов.

2022-12-12 03:37 UTC, ArslanDev666 commented on src/services/initialData.tsx
>      data: {}
**Надо исправить:**

Если значения нет, то нужно использовать `null`, а не пустой объект.

2022-12-13 02:26 UTC, ArslanDev666 requested changes
## Code Review

Здравствуйте!

Отличная работа.

### **Вы молодец!**

- Практически все замечания с прошлого ревью были исправлены;

### **Но ещё есть пару замечаний, которые нужно исправить:**

- https://yadi.sk/d/IwNuoo9SzvuLRQ, по макету, у текста должен быть белый цвет, а также он должен находиться на одной высоте с другим текстом. А у вас он находится чуть ниже.

- Поправьте ховер в хедере, отметил в коде.

2022-12-13 02:26 UTC, ArslanDev666 commented on src/components/app-header/app-header.tsx
>    };
**Надо исправить:**

Не нужно реализовывать ховер таким образом, это плохо сказывается на производительности.
В css есть наследование, .link > svg и .link > a.

2022-12-13 06:33 UTC, Daria989 commented on src/components/app-header/app-header.tsx
>    };
Добрый день! Удалила все useState, но применить ховер к библиотечным компонентам BurgerIcon, ListIcon и ProfileIcon через .link > svg и .link > a. не получается. Им стили задаются через type = "primary" или "secondary". Если я что-то не понимаю, подскажите, пожалуйста, как правильно.

2022-12-13 15:34 UTC, ArslanDev666 commented on src/components/app-header/app-header.tsx
>    };
Добрый вечер)) Ну вообще всё работает :) 

![image](https://user-images.githubusercontent.com/70164458/207375436-ecc2b637-2f53-4b18-b874-457543986d68.png)

Но если стили завязаны на определенном пропсе, то да, лучше конечно не трогать компонент))

Я бы на вашем месте сделал бы на ховер уменьшение `opacity`. 

```css
.link:hover {
  opacity: 0.85;
}
```

2022-12-13 15:34 UTC, ArslanDev666 approved these changes
## Code Review

Здравствуйте!

### **Вы молодец! Работа принята 🔥, удачи в дальнейшем обучении.**

### **Есть пару замечаний, на которые нужно обратить внимание:**

- https://yadi.sk/d/IwNuoo9SzvuLRQ, по макету, у текста должен быть белый цвет)

  - замечание не было исправлено, но там буквально пару строк кода, чтобы это пофиксить и я надеюсь что вы поправите этот момент, поэтому работу принимаю))

- Еще раз хорошо протестируйте авторизацию, что-то она временами хорошо работает, а временами есть мелкие баги, допустим мы можем зайти на страницу профиля и там будут корректные данные, а вот заказ сделать не можем)) Это не супер критично, даже возможно с моей стороны какие-то проблемы), но проверить всё-таки стоит)

2022-12-15 11:11 UTC, merged