Sprint6/step1
Daria989/React-burger pull request #8
Opened 2022-12-20 01:32 UTC by Daria989

2022-12-20 02:39 UTC, ArslanDev666 requested changes
## Code Review

Здравствуйте!

Отличная работа.

### **Вы молодец!**

- Все юнит-тесты (35 шт) проходят успешно
- Все cypress-тесты проходят успешно

### **Но есть несколько замечаний, которые нужно исправить:**

- В cypress тестах, вы не проверяете отображение данных в модальном окне ингредиента;

- Добавьте в package.json скрипт `"cypress:open": "./node_modules/.bin/cypress open"`;

### **Сделает код лучше:**

- Чтобы проверить процент покрытия тестами всех компонентов используйте команду `react-scripts test --coverage --watchAll`.

- Стоит обращать внимание на предупреждения в терминале, в котором запущен проект. Это хорошие рекомендации, которых следовало бы придерживаться. В противном случае, лучше отключить линтер у строки (куска кода) eslint-disable. Так же добавить комментарий (TODO), объясняющий причину блокировки линтера в данном месте. Суть в том, что мы стараемся писать более чистый код, а если видим, что порой выскакивают предупреждения того же линтера, то оставляем комментарий, объясняющий причину. В коммерческой разработке, когда есть целая команда разработчиков, работающих над одним проектом, эта рекомендация послужит правилом хорошего тона. Неплохая статься по поводу локального отключения линтера: https://learn.coderslang.com/ru/0023-eslint-disable-for-specific-lines-files-and-folders

### **_Подробно эти и более мелкие замечания, отмечены в коде._**

2022-12-20 02:39 UTC, ArslanDev666 commented on cypress/e2e/constructorTests.cy.js
> +      cy.get(':nth-child(3) > .input').type('789456123');
**Надо исправить:**

Эти данные лучше вынести в константу.

2022-12-20 02:39 UTC, ArslanDev666 commented on cypress/e2e/constructorTests.cy.js
> +      cy.intercept('POST','https://norma.nomoreparties.space/api/orders', {order: {number: 333987}, success: true}).as('getOrder');
**Надо исправить:**

Апи адрес, а также объект ответа сервеа, тоже нужно вынести в константу.

2022-12-20 02:39 UTC, ArslanDev666 commented on cypress/e2e/constructorTests.cy.js
> +    it('should open and close ingredient modal window', function() {
**Надо исправить:**

вы не проверяете отображение данных в модальном окне ингредиента.

2022-12-20 22:42 UTC, Daria989 commented on cypress/e2e/constructorTests.cy.js
> +      cy.get("[data-testid = link]:eq(10)").drag("[data-testid = dropConstructor]");
Добрый день! Попробовала сделать через each. Тесты проходят, но дропаютсся не все ингредиенты.  Подскажите, пожалуйста, в чем может быть проблема.

2022-12-21 05:41 UTC, ArslanDev666 commented on cypress/e2e/constructorTests.cy.js
> +  const WEB_SERVER_URL = 'http://localhost:3000';
**Можно лучше:**

Лучше вынести за пределы 1 теста, и переиспользовать.

2022-12-21 05:41 UTC, ArslanDev666 commented on cypress/e2e/constructorTests.cy.js
> +    it('should open and close ingredient modal window', function() {
**Можно лучше:** 

Лучше проверять объект ингредиента, т.к. title относиться только к компоненту modal, а не к ingredientsDetails.

2022-12-21 05:41 UTC, ArslanDev666 commented on cypress/e2e/constructorTests.cy.js
> +      cy.get("[data-testid = link]:eq(10)").drag("[data-testid = dropConstructor]");
Доброго времени суток) Там у них была какая-то проблема с `drag` - https://github.com/4teamwork/cypress-drag-drop/issues/89

Если написать явно, то всё будет работать: 

```js
cy.get('[data-testid = link]').each(($el, index) => {
	cy.wrap($el).trigger('dragstart');

	index > 0
		? cy.get('[data-testid = dropConstructor]').trigger('drop')
		: cy.get('[data-testid = dropEmptyBox]').trigger('drop');

	cy.wrap($el).trigger('dragend');
});
```

2022-12-21 05:43 UTC, ArslanDev666 approved these changes
## Code Review

Здравствуйте!

Отличная работа.🔥

### **Вы молодец! Работа принята.**

- Все замечания с прошлого ревью были исправлены.

Несколько советов для дальнейшего развития:

- Сверстайте несколько небольших проектов для себя, для закрепления знаний, и чтобы можно добавить их в портфолио.

- Ходите на собеседования: опыт прохождения собеседований не менее важен знаний теории, и Вы поймете, какие знания требуются на рынке, и где Вы проседаете.

- Читайте habr и слушаете подкаксты: они очень хорошо расширяют кругозор и позволяют узнать, что происходит в отрасли.

2022-12-21 05:43 UTC, ArslanDev666 commented on cypress/e2e/constructorTests.cy.js
> +    email: 'lfif@yandex.ru',
**Можно лучше:**

Лучше вынести за пределы 1 теста, и переиспользовать.

2023-01-18 19:38 UTC, merged